### ISSUE TITLE
Build the proof checker in Cairo

### ISSUE THREAD

**Issue by fiedlr** [Pi-Squared-Network/pi2#399]
- [x] Figure out how to have the checker read input from external sources (need to get this clarified from the Cairo team)
    - The `main` function doesn't seem to support arguments
    - There are no immediately available File IO facilities
    - We may end up having to hard-code inputs and recompile for each example proof

- [x] Based on the outcome of the step above, we will need to either
    - Define the logic that parses command line arguments and reads input from file (or whatever input stream supported), or
    - Define inputs as constant byte arrays in an `inputs` module and use them in the `main` function directly
    
- [x] Develop a representation of the basic data structures: instructions and patterns
    - Try to mimic the definitions given in the rust implementation as much as possible
    - This will involve defining structs, traits, and implementations as needed

- [x] Define terms and pattern construction utility functions
    - Add unit tests

- [x] Define substitution utility functions 
    - Add unit tests

- [x] Define the checker's internal state (stack, memory, …)
    - Add tests if needed
   
- [x] Define the instruction execution function `execute_instructions`
    - By induction on the structure of instructions
    - Add tests for each case

- [x] Define the main verification function for the three execution phases
    
- [x] Run the checker on the various examples we have
    - Make sure the examples pass the checks of the checker
    - Resolve any problems that may arise

- [ ] Benchmark executions
    - Figure out how we may time calls to `verify` (need to get help from the Cairo team)
    - Collect benchmarking results
    - Try to identify performance bottlenecks, if any, and resolve them if possible (feedback from the Cairo team will be helpful here as well)

**Comment by Robertorosmaninho** [comment]
Closing it in favor of #818
